CODE=server.c socket_tool.c cmd.c crc16.c func.c jiliang.c cmd_queue.c  uart_tool.c toplight.c  double_link.c
server:server.c socket_tool.c cmd.c crc16.c func.c jiliang.c cmd_queue.c  uart_tool.c toplight.c  double_link.c
	gcc -o server $(CODE) -lpthread

